### ISSUE TITLE
Cannot start backup: Missing required configuration "internal.key.converter" which has no default value

### ISSUE THREAD

**Issue by Damasker** [itadventurer/kafka-backup#104]
When I start backup
[root@ctrl kafka-backup]# /opt/kafka/bin/backup-standalone.sh --bootstrap-server kafka1:9092 --target-dir /backup/kafka/ --topics 'test-benchmark' --debug
/tmp/kafka-backup.zjmmPc/standalone.properties:
> bootstrap.servers=kafka1:9092
> key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> header.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> key.converter.schemas.enable=false
> value.converter.schemas.enable=false
> offset.storage.file.filename=/tmp/kafka-backup.zjmmPc/kafka-backup.offsets
> offset.flush.interval.ms=10000
> plugin.path=/opt/kafka/bin

/tmp/kafka-backup.zjmmPc/connector.properties:
> name=backup-sink
> connector.class=de.azapps.kafkabackup.sink.BackupSinkConnector
> tasks.max=1
> key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> header.converter=org.apache.kafka.connect.converters.ByteArrayConverter
> target.dir=/backup/kafka/
> max.segment.size.bytes=1073741824
> cluster.bootstrap.servers=kafka1:9092
> topics:test-benchmark

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-serde-tools/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-elasticsearch/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-s3/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-storage-common/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "internal.key.converter" which has no default value.
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:449)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:63)
        at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:163)
        at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:43)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:69)
[root@ctrl kafka-backup]#

**Comment by itadventurer** [comment]
Have you been able to resolve the issue?
I think that may be a problem with the `CLASSPATH`…

**Comment by Damasker** [comment]
No, problem does not resolved.  
Way of installing Kafka have matter?
On test instance, kafka was installed from source. On production(where I have problem) installed from binary.

**Comment by StupidToDie** [comment]
i have the seem problem，did you have solve it

backup-standalone.sh --bootstrap-server localhost:9093 --target-dir /data/kafka_backup --topics 'first,test'
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "internal.key.converter" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:218)
	at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:42)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)

**Comment by Damasker** [comment]
> i have the seem problem，did you have solve it
> 
> backup-standalone.sh --bootstrap-server localhost:9093 --target-dir /data/kafka_backup --topics 'first,test'
> Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "internal.key.converter" which has no default value.
> at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463)
> at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
> at org.apache.kafka.common.config.AbstractConfig.(AbstractConfig.java:62)
> at org.apache.kafka.common.config.AbstractConfig.(AbstractConfig.java:75)
> at org.apache.kafka.connect.runtime.WorkerConfig.(WorkerConfig.java:218)
> at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.(StandaloneConfig.java:42)
> at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)

Hi! What way your kafka is installed?
