### ISSUE TITLE
NPE during backup. Non recoverable

### ISSUE THREAD

**Issue by Guitarkalle** [itadventurer/kafka-backup#108]
Hello,

after a rolling update where partition leader was was switched a couple of times which caused an error very similar (or maybe identical) to https://github.com/itadventurer/kafka-backup/issues/96 the backup service was restarted. After a few hours it crashed again with this Null Pointer. Restarting the backup doesn't work, it just crashes again with the same error.

The logs before the error says this for all topics:
```
[2020-08-07 15:26:57,154] INFO Resetting offset for TOPIC_NAME based upon existing consumer group offsets or, if there are none, the consumer's 'auto.offset.reset' value. (de.azapps.kafkabackup.sink.BackupSinkTask)
```

Exception:
```
[2020-08-07 15:26:58,674] ERROR WorkerSinkTask{id=backup-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
	at de.azapps.kafkabackup.common.offset.OffsetSink.syncOffsetsForGroup(OffsetSink.java:68)
	at de.azapps.kafkabackup.common.offset.OffsetSink.syncOffsets(OffsetSink.java:44)
	at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:75)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-08-07 15:26:59,070] ERROR WorkerSinkTask{id=backup-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at de.azapps.kafkabackup.common.offset.OffsetSink.syncOffsetsForGroup(OffsetSink.java:68)
	at de.azapps.kafkabackup.common.offset.OffsetSink.syncOffsets(OffsetSink.java:44)
	at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:75)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	... 10 more
[2020-08-07 15:26:59,070] ERROR WorkerSinkTask{id=backup-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-08-07 15:26:59,116] INFO Stopped BackupSinkTask (de.azapps.kafkabackup.sink.BackupSinkTask)
```

**Comment by itadventurer** [comment]
If I understand this correctly, this will be fixed by #109

**Comment by Guitarkalle** [comment]
Yes, you can close this one as a duplicate.
I think the kafka client lib should be upgraded also because there has been a fix for negative offsets in the later versions that might benefit this lib.

https://issues.apache.org/jira/browse/KAFKA-9507
