### ISSUE TITLE
Error when restoring consumer-offset topic

### ISSUE THREAD

**Issue by saritago** [itadventurer/kafka-backup#111]
I am getting below error when I try to restore consumer offset topic from the backup. I cleaned up offset topic before trying the offset. Has anyone tried to restore the offfset topic? 
[2020-08-26 08:01:38,048] INFO Read 2 record(s) from topic __consumer_offsets partition 20. Current offset: 4 (de.azapps.kafkabackup.source.BackupSourceTask)
[2020-08-26 08:01:38,081] INFO Read 417 record(s) from topic __consumer_offsets partition 23. Current offset: 38994 (de.azapps.kafkabackup.source.BackupSourceTask)
[2020-08-26 08:01:38,221] INFO All records read. Restore was successful (de.azapps.kafkabackup.source.BackupSourceTask)
[2020-08-26 08:01:38,356] ERROR WorkerSourceTask{id=backup-source-0} failed to send record to __consumer_offsets:  (org.apache.kafka.connect.runtime.WorkerSourceTask)
org.apache.kafka.common.errors.InvalidTopicException: The request attempted to perform an operation on an invalid topic.
[2020-08-26 08:01:38,382] ERROR WorkerSourceTask{id=backup-source-0} failed to send record to __consumer_offsets:  (org.apache.kafka.connect.runtime.WorkerSourceTask)
org.apache.kafka.common.errors.InvalidTopicException: The request attempted to perform an operation on an invalid topic.
[2020-08-26 08:01:38,382] ERROR WorkerSourceTask{id=backup-source-0} failed to send record to __consumer_offsets:  (org.apache.kafka.connect.runtime.WorkerSourceTask)
org.apache.kafka.common.errors.InvalidTopicException: The request attempted to perform an operation on an invalid topic.
[2020-08-26 08:01:38,382] ERROR WorkerSourceTask{id=backup-source-0} failed to send record to __consumer_offsets:  (org.apache.kafka.connect.runtime.WorkerSourceTask)
org.apache.kafka.common.errors.InvalidTopicException: The request attempted to perform an operation on an invalid topic.
[2020-08-26 08:01:43,390] ERROR WorkerSourceTask{id=backup-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 419 messages (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2020-08-26 08:01:43,391] ERROR WorkerSourceTask{id=backup-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Unrecoverable exception from producer send callback
        at org.apache.kafka.connect.runtime.WorkerSourceTask.maybeThrowProducerSendException(WorkerSourceTask.java:282)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.InvalidTopicException: The request attempted to perform an operation on an invalid topic.
[2020-08-26 08:01:43,392] ERROR WorkerSourceTask{id=backup-source-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-08-26 08:01:43,406] INFO Stopped BackupSourceTask (de.azapps.kafkabackup.source.BackupSourceTask)
[2020-08-26 08:01:52,224] ERROR WorkerSourceTask{id=backup-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 419 messages (org.apache.kafka.connect.runtime.WorkerSourceTask)

Also I have a question on how we can run this kafka-backup tool as a cluster? 
I could see that this backup/restore script calls connect-distributed script. Is it possible to use it with connect-distributed utility as well?

**Comment by saritago** [comment]
@itadventurer  Can you have a look at this?
