### ISSUE TITLE
Does this tool support kafka version 0.11.0.3?

### ISSUE THREAD

**Issue by saritago** [itadventurer/kafka-backup#113]
Does this tool support kafka version 0.11.0.3? I have tried using it against version 2.4 and it works fine, but when i try to use it for kafka version, i see below error:
java.lang.NoSuchMethodError: org.apache.kafka.connect.sink.SinkRecord.headers()Lorg/apache/kafka/connect/header/Headers;
        at de.azapps.kafkabackup.common.record.Record.fromSinkRecord(Record.java:51)
        at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:477)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:278)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:195)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2020-10-04 11:58:31,210] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-10-04 11:58:31,210] DEBUG Flushed Topic test-chetan-backup, Partition 0 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,210] DEBUG Flushed Topic test-chetan-backup, Partition 1 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,210] DEBUG Flushed Topic test-chetan-backup, Partition 2 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,210] DEBUG Closed BackupSinkTask for Topic test-backup, Partition 0 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,210] DEBUG Closed BackupSinkTask for Topic test-backup, Partition 1 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,212] DEBUG Closed BackupSinkTask for Topic test-backup, Partition 2 (de.azapps.kafkabackup.sink.BackupSinkTask)
[2020-10-04 11:58:31,212] ERROR Task backup-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:497)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:278)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:195)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2020-10-04 11:58:31,213] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-10-04 11:58:31,213] INFO Stopped BackupSinkTask (de.azapps.kafkabackup.sink.BackupSinkTask)

**Comment by itadventurer** [comment]
Hi, sorry for the very late reply, no it does not work with Kafka versions below 2.4
