### ISSUE TITLE
Restore can fail when at least one partition was empty

### ISSUE THREAD

**Issue by LBmaster001** [itadventurer/kafka-backup#17]
If you have a topic backup where the count of entries is smaller than the count of partitions. You will get an `IndexOutOfBoundsException` when you try to restore the backup of the topic. Error message is `Could not find offset 0 in topic test01, segment segment_partition_005_from_offset_0000000000` Maybe you add a flag when storing the partition, that it is empty, or you modify how empty partitions are handled (e.g. printing a warning message to the log).
Full Stacktrace:
```
java.lang.IndexOutOfBoundsException: Could not find offset 0 in topic test01, segment segment_partition_005_from_offset_0000000000
        at de.azapps.kafkabackup.common.segment.SegmentReader.seek(SegmentReader.java:50)
        at de.azapps.kafkabackup.common.partition.PartitionReader.seek(PartitionReader.java:49)
        at de.azapps.kafkabackup.common.partition.PartitionReader.<init>(PartitionReader.java:34)
        at de.azapps.kafkabackup.source.BackupSourceTask.lambda$findPartitions$0(BackupSourceTask.java:85)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at de.azapps.kafkabackup.source.BackupSourceTask.findPartitions(BackupSourceTask.java:79)
        at de.azapps.kafkabackup.source.BackupSourceTask.start(BackupSourceTask.java:46)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by itadventurer** [comment]
I see whats the problem… The [`SegmentReader::seek()`](https://github.com/itadventurer/kafka-backup/blob/master/src/main/java/de/azapps/kafkabackup/common/segment/SegmentReader.java#L47) function should check whether the file is empty and in case the file is empty it should not throw the exception. (I do not think it should log a warning at all because this should be the intended behaviour)

**Comment by rohan26may** [comment]
Similar issue for me,

I have Kafka 2.3.1 cluster and able to take periodic backups from Kafkabackup tool on another standalone Kafka 2.4.0.
However when I try to restore this backup to either of 2.3.1 Cluster or 2.4.0 Standalone, the backup fails with following error.

Another thing that I have noticed that the backup process did not create /tmp/connect.offsets file... not sure if this is related???

Please advise.

`[2020-02-25 10:58:45,467] ERROR WorkerSourceTask{id=backup-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
java.lang.IndexOutOfBoundsException: Could not find offset 0 in topic Test_Topic, segment segment_partition_028_from_offset_0000000000 ok Optional.empty
        at de.azapps.kafkabackup.common.segment.SegmentReader.seek(SegmentReader.java:50)
        at de.azapps.kafkabackup.common.partition.PartitionReader.seek(PartitionReader.java:49)
        at de.azapps.kafkabackup.common.partition.PartitionReader.<init>(PartitionReader.java:34)
        at de.azapps.kafkabackup.source.BackupSourceTask.lambda$findPartitions$0(BackupSourceTask.java:85)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at de.azapps.kafkabackup.source.BackupSourceTask.findPartitions(BackupSourceTask.java:79)
        at de.azapps.kafkabackup.source.BackupSourceTask.start(BackupSourceTask.java:46)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by rohan26may** [comment]
Please review and merge if changes are OK.
https://github.com/itadventurer/kafka-backup/pull/19

**Comment by LBmaster001** [comment]
I think the issue is here:
https://github.com/itadventurer/kafka-backup/blob/3c95089c699af6b42207925b05ff04a721da95e1/src/main/java/de/azapps/kafkabackup/common/partition/PartitionWriter.java#L34
Here you tell the `SegmentWriter` to write the startoffset of 0, but no content is written to the Record file.
The Problem is, that a startOffset of zero is a valid option since you start to count at zero so the Reader will later think there has to be some data it can read.
If the Data read is empty, you will receive the error posted above.
My Idea is to again have something that tells the reader, that there is empty data by changing the line from 
```java
currentSegment = new SegmentWriter(topic, partition, 0, topicDir);
```
to
```java
currentSegment = new SegmentWriter(topic, partition, -1, topicDir);
```
and insert a check when reading the startOffset

**Comment by itadventurer** [comment]
Should work now (https://github.com/itadventurer/kafka-backup/commit/1c200daced7fc8f514afc4f6f5215954e4b819f4), tests will come with #20. Please reopen if issue persists
