### ISSUE TITLE
NullpointerException when Record Timestamp is null

### ISSUE THREAD

**Issue by fubezz** [itadventurer/kafka-backup#40]
First of all thanks for this project! 
When performing a kafka backup, it fails with nullpointer exception because of the first record of a topic has a "null" timestamp:

    Record{topic: kafka.backup.status, partition: 3, offset: 82, key: byte[31], value: byte[79], timestampType: CreateTime, timestamp: 1585135162346, headers: ConnectHeaders(headers=)}
    Record{topic: kafka.backup.status, partition: 3, offset: 83, key: byte[31], value: byte[82], timestampType: CreateTime, timestamp: 1585135165458, headers: ConnectHeaders(headers=)}
    Record{topic: kafka.backup.status, partition: 3, offset: 84, key: byte[31], value: byte[79], timestampType: CreateTime, timestamp: 1585135732945, headers: ConnectHeaders(headers=)}
    Record{topic: kafka.backup.status, partition: 3, offset: 85, key: byte[31], value: byte[1537], timestampType: CreateTime, timestamp: 1585135737340, headers: ConnectHeaders(headers=)}
    Record{topic: kafka.backup.status, partition: 3, offset: 86, key: byte[31], value: byte[79], timestampType: CreateTime, timestamp: 1585136057716, headers: ConnectHeaders(headers=)}
    Record{topic: cdc.minio.autoportal, partition: 0, offset: 0, key: byte[42], value: byte[1166], timestampType: CreateTime, timestamp: null, headers: ConnectHeaders(headers=)}
    [2020-03-25 11:34:22,187] ERROR WorkerSinkTask{id=kafka-backup-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
    java.lang.NullPointerException
            at de.azapps.kafkabackup.common.record.RecordSerde.write(RecordSerde.java:102)
            at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:75)
            at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
            at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:68)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
            at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
            at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

I fixed the problem by changing de.azapps.kafkabackup.common.record.RecordSerde.java:
```
 public static void write(OutputStream outputStream, Record record) throws IOException {
        Converter converter = new AlreadyBytesConverter();
        DataOutputStream dataStream = new DataOutputStream(outputStream);
        dataStream.writeLong(record.kafkaOffset());
        dataStream.writeInt(record.timestampType().id);
        if (record.timestampType() != TimestampType.NO_TIMESTAMP_TYPE) {
            if (record.timestamp() != null){
                dataStream.writeLong(record.timestamp());
            }else{
                dataStream.writeLong(0);
            }

        }
...
```
Actually I am not sure if  I messed up my records or if it is a bug in the code
Greetings

**Comment by itadventurer** [comment]
Hi, thank you :)
When did you build Kafka Backup. This should be already fixed on master for a week or so ;) 

https://github.com/itadventurer/kafka-backup/blob/master/src/main/java/de/azapps/kafkabackup/common/record/RecordSerde.java#L99-L102

**Comment by fubezz** [comment]
I just pulled and rebuilt it. The problem seems to be solved!
I must have missed the update by on day or so :)
Thank you!
