### ISSUE TITLE
Sink connector not apennding backup file

### ISSUE THREAD

**Issue by JurajBonk** [itadventurer/kafka-backup#41]
Steps done:

1. Configured  the sink connector
2. Checked the size of the backup file
3. Manually added data to Kafka topic

```json
"tasks": [{
    "state": "FAILED",
    "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: de.azapps.kafkabackup.common.segment.SegmentWriter$SegmentException: Trying to override a written record. There is something terribly wrong in your setup! Please check whether you are trying to override an existing backup
       at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:77)
       at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
       ... 10 more
Caused by: de.azapps.kafkabackup.common.segment.SegmentWriter$SegmentException: Trying to override a written record. There is something terribly wrong in your setup! Please check whether you are trying to override an existing backup
       at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:72)
       at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
       at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:68)
       ... 11 more
",
    "id": 0,
    "worker_id": "kafka-connect:8083"
  }],
```

**Comment by itadventurer** [comment]
Hi Juraj,
I was able to reproduce the error. It is quite nasty:

Steps to reproduce:

## Part 1

* Start with a fresh Kafka Cluster
* Produce some messages (lets say 100)
* Backup the messages
* Kill the cluster and delete all data (BUT NOT THE BACKUP)

## Part 2

* Start a fresh Kafka Cluster (again)
* Produce some messages (less than in the first part! – lets say 50)
* Start Kafka Backup

## What happens?

* Kafka Backup tries to reset to offset 100
* This fails transparently (there is no exception raised) – because that is an invalid offset
* The offset stays at `0`
* Kafka Backup tries to write a message with the offset `0`. That fails (This is good!) with the message above

## Next steps

* [ ] I will Improve the error message. I will add something like "Did you forget to delete a previous backup?"
* [ ] I will add a test case to check whether something like the following works (It should work perfectly fine – lets verify that with a real test)
  * start a backup connector
  * let it run for some time
  * delete it
  * create a new one with the same source and destination


## General potential pitfall (not specific to Kafka Backup)

Kafka Backup identifies messages only according to the offset in a partition. I.e. the following scenario will lead to a bad result (and it should! There is no way for Kafka to avoid that. This would be a human error to do something like this!):

* Write 50 messages
* Backup them
* Delete Cluster, create new one
* Write 100 other messages in the empty topic

⇒ Kafka Backup will keep the old first 50 messages


I hope this helps.

**Comment by JurajBonk** [comment]
Hi Anatoly, thank you for the answer, but in our setup this bug happens even "in one run" without restarting the kafka cluster.

**Comment by itadventurer** [comment]
Hmm… weird. Try to update Kafka Backup to the newest version and do a new build. At the very least you will get more debugging information ;)

**Comment by itadventurer** [comment]
Do you have any news regarding this? Please reopen the ticket if it is not solved.
