### ISSUE TITLE
Errors during the backup process

### ISSUE THREAD

**Issue by akamensky** [itadventurer/kafka-backup#60]
```
[2020-04-17 16:34:18,557] ERROR WorkerSinkTask{id=backup-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
org.apache.kafka.connect.errors.DataException: Topic1 error: Not a byte array! q�0�
	at de.azapps.kafkabackup.common.AlreadyBytesConverter.fromConnectData(AlreadyBytesConverter.java:19)
	at de.azapps.kafkabackup.common.record.RecordSerde.write(RecordSerde.java:121)
	at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:78)
	at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
	at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:68)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-04-17 16:34:18,567] ERROR WorkerSinkTask{id=backup-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Topic1 error: Not a byte array! q�0�
	at de.azapps.kafkabackup.common.AlreadyBytesConverter.fromConnectData(AlreadyBytesConverter.java:19)
	at de.azapps.kafkabackup.common.record.RecordSerde.write(RecordSerde.java:121)
	at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:78)
	at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
	at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:68)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
	... 10 more
[2020-04-17 16:34:18,568] ERROR WorkerSinkTask{id=backup-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
```

**Comment by itadventurer** [comment]
Hi,
is it a message with headers? If so I am on it ;) see #57

**Comment by akamensky** [comment]
I have no idea if message is with headers that is written by developers, I am just trying to use the tool to make backups on production data as a test.

**Comment by itadventurer** [comment]
Then I will close it for now and I'd the big still occurs after #57 is closed we would need to check again.
